import { z } from "zod";

export const baseMessageSchema = z.object({
  messageId: z
    .string()
    .describe(
      "Unique id for the message, generated by the client. Can be used to match the response.",
    ),
});

export type BaseMessage = z.infer<typeof baseMessageSchema>;
